import React from 'react';
import ReactDOM from 'react-dom';

// import './001-基本用法.js'
// import './002-基本JSX语法.js'
// import './003-JSX的语法细节.js'
// import './004-函数式组件.js'
// import './006-class方式创建组件.js'
// import './007-this-state'
// import './008-demo~评论列表组件.js'
// import './009-点击事件.js'
// import './010-setState.js'
// import './011-state和事件函数的简写方式.js'
// import './012-props'
// import './013-props传递类型的限制'
// import './014-refs.js'
// import './015-回调函数形式的ref.js'
// import './016-回调ref的回调执行次数'
// import './017-createRef'
// import './018-生命周期（旧）'
// import './019-生命周期（新）'
// import './020-DOM的diff算法'
// import './021-key的作用'
// import './demo.js'
// import './手动保存数据.js'
// import './setState接收一个函数.js'
// import './hook-001-useState';
// import './hook-002-切换'
// import './hook-003-输入变化'
// import './hook-004-useEffect'
// import './ahooks-001-test'
// import './ahooks-002-useRequest'
// import './flooks-01'
// import './flooks-02'
// import './flooks-03'
// import './flooks-04'
// import './test-style-components-001.js'
// import './test-style-components-002.js'
// import './test-style-components-003.js'
// import './test-style-components-004-组件样式化'
// import './test-style-components-005-&符号'
// import './ubstated-001-hello'
// import './unstated-next-001'

import './demos/sidebar-01';
